steps:
  - label: run bats tests
    plugins:
      docker-compose#v3.0.1:
        run: tests

  - label: ":bash: Shellcheck"
    plugins:
      shellcheck#v1.1.1:
        files:
          - hooks/*

  - label: ":sparkles: Linter"
    plugins:
      plugin-linter#v2.0.0:
        id: golang

  - label: test running a specific version
    command: go version
    plugins:
      ${BUILDKITE_REPO}#${BUILDKITE_COMMIT}:
        version: 1.10.2

  - label: test cross compiling
    command: go build ./tests/helloworld
    plugins:
      ${BUILDKITE_REPO}#${BUILDKITE_COMMIT}:
        version: 1.10.2
        environment:
          - GOOS=android
          - GOARCH=arm
          - GOARM=7




