steps:
  - label: run bats tests
    plugins:
      - plugin-tester#v1.0.0: ~

  - label: ":bash: Shellcheck"
    plugins:
      - shellcheck#v1.3.0:
          files:
            - hooks/*

  - label: ":sparkles: Linter"
    plugins:
      - plugin-linter#v3.0.0:
          id: golang

  - label: test running a specific version
    command: go version
    plugins:
      - ${BUILDKITE_REPO}#${BUILDKITE_COMMIT}:
          version: 1.13.8

  - label: test cross compiling
    command: go build ./tests/helloworld
    plugins:
      - ${BUILDKITE_REPO}#${BUILDKITE_COMMIT}:
          version: 1.13.8
          environment:
            - GOOS=linux
            - GOARCH=arm
            - GOARM=7
