#!/bin/bash
set -euo pipefail

if [[ "${BUILDKITE_PLUGIN_GOLANG_DEBUG:-false}" =~ (true|on|1) ]] ; then
  echo "--- :hammer: Enabling debug mode"
  env | sort | grep BUILDKITE_PLUGIN_GOLANG
fi

go_version="${BUILDKITE_PLUGIN_GOLANG_VERSION:-latest}"
pkg="${BUILDKITE_PLUGIN_GOLANG_PACKAGE:-${BUILDKITE_PIPELINE_SLUG}}"

args=(
  "--rm"
  "--volume" "$PWD:/go/src/${pkg}"
  "--workdir" "/go/src/${pkg}"
)

# Parse extra env vars and add them to the docker args
while IFS='=' read -r name _ ; do
  if [[ $name =~ ^(BUILDKITE_PLUGIN_GOLANG_ENVIRONMENT_[0-9]+) ]] ; then
    args+=( "--env" "${!name}" )
  fi
done < <(env | sort)

echo "+++ :go: Running ${BUILDKITE_COMMAND} in golang:${go_version}"

docker run "${args[@]}" "golang:${go_version}" sh -c "${BUILDKITE_COMMAND}"
